name: Black formatter

on: [push, pull_request]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'
      - name: Get pip cache dir
        id: pip-cache
        shell: bash
        run: |
          echo "dir=$(pip cache dir)" >> $GITHUB_OUTPUT
      - name: Caching python pip requirements
        uses: actions/cache@v4.2.0
        with: 
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip(python${{ matrix.python-version }})-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip(python3.11)-
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black[jupyter]
      - name: Format files
        run: black --verbose .
      - name: Push new changes
        run: |
          git config user.name "Github Actions"
          git config user.email "nonuser@email"
          git commit -m "Fix: Reformat code using Black"
          git push https://{{ secrets.GITHUB_TOKEN }}@github.com/{{ github.repository }}.git
